[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "f5c4b0429a99c4251de42080d1f22f26515449bc"
os = "macos"

    [[GAP_pkg_gauss.download]]
    sha256 = "7e1412a0dc005ad299aa3b7371a79b724b258e8a154316a161acc5e79b5de6b3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.102+0/GAP_pkg_gauss.v202400.1100.102.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "7e7aadba7df5087bed0159d38447a2699a0d38e6"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "869ef72f92d05527f8e866535d649fd909016c20c913ae184f59961ea3a1c078"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.102+0/GAP_pkg_gauss.v202400.1100.102.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "abc476bacc39f8533ffe13995d9d3319a79e89b1"
libc = "musl"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "870ff6939bb82c4874c8284d49515eae088019ac62f9f8032ab82e63019bc70d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.102+0/GAP_pkg_gauss.v202400.1100.102.aarch64-linux-musl.tar.gz"
[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "4b35dbb848fac480eb0b81969b948e5542d406f9"
os = "freebsd"

    [[GAP_pkg_gauss.download]]
    sha256 = "ae0c9ffb549a6f15e6003294cda5b6ab13bddcc0c8fe9f698e2ad3124516310e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.102+0/GAP_pkg_gauss.v202400.1100.102.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_gauss]]
arch = "powerpc64le"
git-tree-sha1 = "2378a5987392eafb8f4b04a46aaee0e50c2fde37"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "af38ce8177397ec6f776b48dc33480a57859aed1f1f7cbf73604addabc19a662"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.102+0/GAP_pkg_gauss.v202400.1100.102.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "riscv64"
git-tree-sha1 = "30822f004345c9bc3142903737cc83bd0054e0ca"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "ffabaab0f9f3403f3d9b046ecc7d3f405f7df834e2e18603e7c867686b83e247"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.102+0/GAP_pkg_gauss.v202400.1100.102.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "c7983497fbd5a98cc1e4f696f1ec56ef56f3f666"
os = "macos"

    [[GAP_pkg_gauss.download]]
    sha256 = "586fe4bf716ed3abcafe8a80433a02859a07a904827ad1655bb2d102a13d1704"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.102+0/GAP_pkg_gauss.v202400.1100.102.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "71b35f5ba4d7df05c3ced1f4cfd028bbc36fe819"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "4d93556d060621acdbb7798558ba94c7a151126ea65d4c39e072b912277e2a6b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.102+0/GAP_pkg_gauss.v202400.1100.102.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "9e71b12791f906cf81b79c726ab4176dd03a8581"
libc = "musl"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "f9f05b9a1645a8ab8709e9126a473f1c2a7d002a6be3e6ea3c8b4fcb63aad2f6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.102+0/GAP_pkg_gauss.v202400.1100.102.x86_64-linux-musl.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "25224eb419ce64deb9ead11b2e0380d672232d98"
os = "freebsd"

    [[GAP_pkg_gauss.download]]
    sha256 = "e53e6d57cc62f78b5c1f394b2a54eecc8a38172e8d3c96d485104f8c1573e6b6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.102+0/GAP_pkg_gauss.v202400.1100.102.x86_64-unknown-freebsd.tar.gz"
