[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "ccf4c7e08a45f533f4c98de7e27edd7251b5ac0d"
os = "macos"

    [[GAP_pkg_gauss.download]]
    sha256 = "374c336b4e9d682c5b90e3abf969f3308c3e07f45c59aa36db9ac0e8df9f198b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202300.200.400+0/GAP_pkg_gauss.v202300.200.400.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "75e0463794edd445b8a41a4ac21950d34052ed0c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "8bb56ba433d3da370ff87c2459d146630f787d42bc5cc84f94054e2db4b9759c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202300.200.400+0/GAP_pkg_gauss.v202300.200.400.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "9afaa78680e6c8c5d71ba0b7fc65a5eff5680fe1"
libc = "musl"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "bc1a0369318358f73d1afc775e99ef5d48e041bc6c4473c05abff2a5e14d777e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202300.200.400+0/GAP_pkg_gauss.v202300.200.400.aarch64-linux-musl.tar.gz"
[[GAP_pkg_gauss]]
arch = "powerpc64le"
git-tree-sha1 = "d79846ac482189ab5234a0e436eb60407341003a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "63e01db70ae95162c3a92e46d1f3e9f6571aa256df19e076907bd1087e66cc02"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202300.200.400+0/GAP_pkg_gauss.v202300.200.400.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "62ab397645c86116e39aad1e3e1edaa56940d15e"
os = "macos"

    [[GAP_pkg_gauss.download]]
    sha256 = "bab5fb91e40d9eaac64babd0d9b1fb4a60fa086b40f12ab7cac89f78f44e6e75"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202300.200.400+0/GAP_pkg_gauss.v202300.200.400.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "987928dff4794bfa041609e1ab74c9670b4649ac"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "f13a29e367317a086dd5b0b17e19874bd15f728c243e8f7fb187326ed34319cb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202300.200.400+0/GAP_pkg_gauss.v202300.200.400.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "fdd972ed3e66ab3108d83b3c7a17d8dc41f5ab79"
libc = "musl"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "3ffcc75d3c2e5781b67089c0dc7db0c01de31b2f0f6e64491348678bd959b082"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202300.200.400+0/GAP_pkg_gauss.v202300.200.400.x86_64-linux-musl.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "aeb0765c5bb64e1a864fe64b21265fd6383713a3"
os = "freebsd"

    [[GAP_pkg_gauss.download]]
    sha256 = "d40bc2f96b7ead132ca1f5bd9cec5ab489391bdd4a7c8feaa14f6444d750e504"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202300.200.400+0/GAP_pkg_gauss.v202300.200.400.x86_64-unknown-freebsd.tar.gz"
