[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "540c9ebbeac164617efb6e9323ddc543f20e6a40"
os = "macos"

    [[GAP_pkg_gauss.download]]
    sha256 = "ec2589b27c401c00c1dccc162a48adbfe31ca5564cedfad4bbd6913178fda8d6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202401.110100.0+0/GAP_pkg_gauss.v202401.110100.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "b4d9c2676db5569d5ccde589894fb5e553eef5a4"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "0c3087331d8cfea353c9159ae0c99e612cb43d9f4530055e4418b5e1a0f48b70"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202401.110100.0+0/GAP_pkg_gauss.v202401.110100.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "530ac0af246f30a2071137bdf4e2b197edeb120f"
libc = "musl"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "f397adf9a74ad23337be370189dae095d70b26bc36f5c939cb13550c3e168ade"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202401.110100.0+0/GAP_pkg_gauss.v202401.110100.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "52eb582e24001d189ec3ba977e6081b5acbcbaea"
os = "freebsd"

    [[GAP_pkg_gauss.download]]
    sha256 = "502142da03872fc1216d5845fb8ba93db8361db346f7ca58d04942be074ed070"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202401.110100.0+0/GAP_pkg_gauss.v202401.110100.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_gauss]]
arch = "powerpc64le"
git-tree-sha1 = "65b3a7ba6f4855222f3ae3a8be9b86bb9e5a7c66"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "fe6d30850e0e64b10fa8d912623968fc8095d29a6daa40af6a8a58afb70eea2c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202401.110100.0+0/GAP_pkg_gauss.v202401.110100.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "riscv64"
git-tree-sha1 = "357cd60af414dab7e98fd2a0ab1e5f704d05555a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "e2efecf9c64cc2aeb3e40e908373dc628b5da17d23399c8aa19d45469c99af40"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202401.110100.0+0/GAP_pkg_gauss.v202401.110100.0.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "a55a767205124dca95239f0904ca8bac5cca9016"
os = "macos"

    [[GAP_pkg_gauss.download]]
    sha256 = "5eb878614424e053d729129afa61089aec533d619caec20a10e277687e064899"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202401.110100.0+0/GAP_pkg_gauss.v202401.110100.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "b7edde83ead0f05ca0d08ee9600560393a0f6251"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "b4202f9bd5a2f632a91cad5133294eb75d424e879296b2c731eed4b051136b59"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202401.110100.0+0/GAP_pkg_gauss.v202401.110100.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "83acf3da514486bfb481b31a75cfa65ff48c9ace"
libc = "musl"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "c41ee464f39ab87da804f69e28badc9c1f98bd067f113bd31c88c21117cb677b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202401.110100.0+0/GAP_pkg_gauss.v202401.110100.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "3829c8318d8be47e5451390b6cc7b67187483361"
os = "freebsd"

    [[GAP_pkg_gauss.download]]
    sha256 = "dcc674d91e59b4af51cef838728a1a6a246f789b149436a2a4eecb9ad9344bd4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202401.110100.0+0/GAP_pkg_gauss.v202401.110100.0.x86_64-unknown-freebsd.tar.gz"
