[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "a0ee5550b1dafa024e102b19f5a5e7d7ac39134f"
os = "macos"

    [[GAP_pkg_gauss.download]]
    sha256 = "40e0790aec17d9b5379ce99aca811e8c516d9898bf24dc1ff8111cee3b0a79b9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.100+1/GAP_pkg_gauss.v202400.1100.100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "81445a44d517aa5e6cf1555cc05935a5e1502305"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "1f7e4f359fef8febe493d97a4720d2b93f24d2cc955928718ce297c5bebe917f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.100+1/GAP_pkg_gauss.v202400.1100.100.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "46c248140665d795026fab1e2b813f53b0027f8a"
libc = "musl"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "2ad9ff8009e71d3061e66a92dfe542129264826802c872c0e4f4fafa7f56cf89"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.100+1/GAP_pkg_gauss.v202400.1100.100.aarch64-linux-musl.tar.gz"
[[GAP_pkg_gauss]]
arch = "powerpc64le"
git-tree-sha1 = "66124d3bd0d54d0c4e4429793925b6f4a1c6f47c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "9067ad6acebd06e865df8a41bfd81994c495ab5b192abf3cf07d4fde3cfc88d5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.100+1/GAP_pkg_gauss.v202400.1100.100.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "a077f2c0a77f21cd9cd490380ee15ee01c2d6d3d"
os = "macos"

    [[GAP_pkg_gauss.download]]
    sha256 = "90fc94b67b73278205e75ffe98c6f460e6bd587fdf2ee34122117f9167dc9d89"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.100+1/GAP_pkg_gauss.v202400.1100.100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "59d6252fd04d8035d708d603b90157834e97ec59"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "a9b391e0031f2d78afacddbf58caaeebb914045b255393683069d7c17d29fa7e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.100+1/GAP_pkg_gauss.v202400.1100.100.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "4790ac323f3ddd48de607ec55f946d6f11a83cd1"
libc = "musl"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "069d8ca833312dbf81ad74addb9252794b28f76b933c0274e63dd52c2f7382cc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.100+1/GAP_pkg_gauss.v202400.1100.100.x86_64-linux-musl.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "07a809de638ca4a0bf1ba76f7aa63db9dcbb42c7"
os = "freebsd"

    [[GAP_pkg_gauss.download]]
    sha256 = "fd52aead76ad9f00bf72b3506e7a395323a488ac3944ed50ce6fd6d25a78ec99"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.100+1/GAP_pkg_gauss.v202400.1100.100.x86_64-unknown-freebsd.tar.gz"
