[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "31d55e584125107c89967aabf62045a9dd989696"
os = "macos"

    [[GAP_pkg_gauss.download]]
    sha256 = "4deb15abe565d03782ad75f6eab0e0d39630564fab65592ef26318816040e273"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.101+0/GAP_pkg_gauss.v202400.1100.101.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "503dbf5bb2077c417ed039c1568926a06186cb14"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "9d088c8d8759d0e74bab71ba31ac948c4604cc799eb84c8bec8576a40177560a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.101+0/GAP_pkg_gauss.v202400.1100.101.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "ca181cf32d0b87ef6f62d3c75ac818d0d1a4ac92"
libc = "musl"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "b6dcaae1af3479393c79710987058ab94e771ea1693f66e90a1c1926b876caaf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.101+0/GAP_pkg_gauss.v202400.1100.101.aarch64-linux-musl.tar.gz"
[[GAP_pkg_gauss]]
arch = "aarch64"
git-tree-sha1 = "d827ebd03dcd1a880151cc18d1e0aee836d0b796"
os = "freebsd"

    [[GAP_pkg_gauss.download]]
    sha256 = "59755f5e383dfb8278a7f312a17fbe13f2b86a819fa32e8e6c78e427dcef6b66"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.101+0/GAP_pkg_gauss.v202400.1100.101.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_gauss]]
arch = "powerpc64le"
git-tree-sha1 = "800e22ebd4d80a870b5eeefbd2ea23407d195e5f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "3cb4af8334125679cf0e8bf43f493c7a6b43d36eb0e764bf243f88abdabbb9dd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.101+0/GAP_pkg_gauss.v202400.1100.101.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "riscv64"
git-tree-sha1 = "3d87545ccb3717c1f8cf57837c6ce1c8ad71c7cc"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "d717b27950c84e9ec9e97a4f277d0a6fbc5fa7b87bd713f768795de98e625d90"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.101+0/GAP_pkg_gauss.v202400.1100.101.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "44404576af6c178188e78b324b9369e2ccd9d03f"
os = "macos"

    [[GAP_pkg_gauss.download]]
    sha256 = "af57cea30c671aeb244ca8917a0f54843bacf23c7dd073861d0632befb8d5405"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.101+0/GAP_pkg_gauss.v202400.1100.101.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "35924a32d21d80d2ccfd04c1ff3f64b1c85176a2"
libc = "glibc"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "e868f688607014006fd363a44ee396ab02af414d76295353045e9c52fcb3f8d7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.101+0/GAP_pkg_gauss.v202400.1100.101.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "6d1385dff92053e61387ceb5c79b15993bebbc08"
libc = "musl"
os = "linux"

    [[GAP_pkg_gauss.download]]
    sha256 = "6623d3dca43801e4bb11c75a332dc1f333a5473224d8547fe742cecb1dba26ed"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.101+0/GAP_pkg_gauss.v202400.1100.101.x86_64-linux-musl.tar.gz"
[[GAP_pkg_gauss]]
arch = "x86_64"
git-tree-sha1 = "cd1adc36a22129cf2ff7cf99849d4789c44a8f8c"
os = "freebsd"

    [[GAP_pkg_gauss.download]]
    sha256 = "fc1e4166e05a025d1c12f8ab995cce4270993f1d48bc1b23c37331683fd96dfe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_gauss_jll.jl/releases/download/GAP_pkg_gauss-v202400.1100.101+0/GAP_pkg_gauss.v202400.1100.101.x86_64-unknown-freebsd.tar.gz"
